import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Navbar from "@/components/Navbar";
import * as React from "react";
import Tooltip from "@mui/material/Tooltip";
import { Separator } from "@/components/ui/separator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashbordLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        data-new-gr-c-s-check-loaded="14.1229.0"
        data-gr-ext-installed=""
        cz-shortcut-listen="true"
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="w-full px-1">
            <div className="flex gap-3">
              <Tooltip title="Ctrl+B">
                <SidebarTrigger />
              </Tooltip>
              <Navbar />
            </div>
            <Separator />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
